apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    lingo: enabled
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
