{{- if and .Values.secrets.huggingface.create (not .Values.secrets.huggingface.token) -}}
{{ fail "secrets.huggingface.token must be set if secrets.huggingface.create is true" }}
{{- end }}
{{- if .Values.secrets.huggingface.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeai.huggingfaceSecretName" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
data:
  token: {{ .Values.secrets.huggingface.token | b64enc }}
{{- end }}