name: Integration Tests
run-name: Integration Tests by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run system test kind
          run: make test-integration
